### ISSUE TITLE
Problème exercice 3

### ISSUE THREAD

**Issue by vddk19** [CMzk10/Exercices-en-Java#3]
J'ai un problème avec l'ex3. Mon code ne renvoie pas les résultats attendus. Possible d'y jeter un coup d'oeil? 
en copie mon output dans la console
![image](https://user-images.githubusercontent.com/72493990/95994948-2f056080-0e31-11eb-949b-711c3c1c52e5.png)

**Comment by CMzk10** [comment]
J'y regarde envoie moi le code

**Comment by vddk19** [comment]
C'est fait. Merci :)
